blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/yidafu/swc-binding/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://yidafu.github.io/swc-binding/docs/
    about: Check out our documentation

